--------------------------------------------------------
--  File created - Tuesday-April-30-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CART
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."CART" 
   (	"ID" NUMBER(5,0), 
	"USERNAME" VARCHAR2(50 BYTE), 
	"PRODUCTID" NUMBER(5,0), 
	"QUANTITY" NUMBER(5,0), 
	"TOTAL" NUMBER(10,2)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.CART
SET DEFINE OFF;
Insert into SYSTEM.CART (ID,USERNAME,PRODUCTID,QUANTITY,TOTAL) values (30,'Sample user',1,4,1596);
--------------------------------------------------------
--  DDL for Index CART_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."CART_PK" ON "SYSTEM"."CART" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger CART_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SYSTEM"."CART_TRIGGER" BEFORE INSERT ON cart FOR EACH ROW BEGIN SELECT cart_seq.NEXTVAL INTO :new.id FROM dual; END;
/
ALTER TRIGGER "SYSTEM"."CART_TRIGGER" ENABLE;
--------------------------------------------------------
--  Constraints for Table CART
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."CART" ADD CONSTRAINT "CART_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."CART" MODIFY ("TOTAL" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CART" MODIFY ("QUANTITY" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CART" MODIFY ("PRODUCTID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CART" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CART" MODIFY ("ID" NOT NULL ENABLE);
