--------------------------------------------------------
--  File created - Tuesday-April-30-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ORDERS
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."ORDERS" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(255 BYTE), 
	"EMAIL" VARCHAR2(255 BYTE), 
	"CONTACTNUMBER" VARCHAR2(20 BYTE), 
	"ADDRESS" VARCHAR2(255 BYTE), 
	"CITY" VARCHAR2(100 BYTE), 
	"TOTAL" NUMBER(10,2), 
	"USERNAME" VARCHAR2(255 BYTE), 
	"CREATEDAT" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.ORDERS
SET DEFINE OFF;
Insert into SYSTEM.ORDERS (ID,NAME,EMAIL,CONTACTNUMBER,ADDRESS,CITY,TOTAL,USERNAME,CREATEDAT) values (7,'test','test@test.com','12312','1231','123',null,'testuser',to_date('04/30/2024','MM/DD/RRRR'));
Insert into SYSTEM.ORDERS (ID,NAME,EMAIL,CONTACTNUMBER,ADDRESS,CITY,TOTAL,USERNAME,CREATEDAT) values (8,'test','test@test.com','12312','1231','123',null,'testuser',to_date('04/30/2024','MM/DD/RRRR'));
Insert into SYSTEM.ORDERS (ID,NAME,EMAIL,CONTACTNUMBER,ADDRESS,CITY,TOTAL,USERNAME,CREATEDAT) values (9,'test','test@test.com','12312','1231','123',null,'testuser',to_date('04/30/2024','MM/DD/RRRR'));
--------------------------------------------------------
--  DDL for Index SYS_C007011
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C007011" ON "SYSTEM"."ORDERS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger ORDER_ID_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SYSTEM"."ORDER_ID_TRIGGER" 
BEFORE INSERT ON orders
FOR EACH ROW
BEGIN
    SELECT order_id_seq.NEXTVAL INTO :new.id FROM dual;
END;
/
ALTER TRIGGER "SYSTEM"."ORDER_ID_TRIGGER" ENABLE;
--------------------------------------------------------
--  Constraints for Table ORDERS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."ORDERS" MODIFY ("CREATEDAT" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."ORDERS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
